### ISSUE TITLE
Payara Micro configuration is not most optimal one

### ISSUE THREAD

**Issue by rdebusscher** [rmh78/quarkus-performance#2]
The Payara Micro configuration is not the most optimal configuration.  By default, it is optimized for a clustered setup as in Kubernetes.

Please add also --noCluster as key (https://github.com/rmh78/quarkus-performance/blob/master/demo-payara/pom.xml#L44)

And even then, it is not the most optimal and even further tuning is possible.

**Comment by haraldatbmw** [comment]
For sure there are many tuning options for all configurations and all java runtimes too. In my comparison I use the default behavior.

For the Payara Micro configuration the --noCluster argument is already set at start-time of the uber-jar. See https://github.com/rmh78/quarkus-performance/blob/master/test-all.sh#LL23
